"""Train the RockGuard AI risk model on the SYNTHETIC dataset.

Run from the backend directory:

    python -m app.ml.train_model

Writes `app/ml/artifacts/risk_model.joblib` plus a metrics JSON.

The reported metrics describe performance on held-out SYNTHETIC data only.
They say how well the model recovered the artificial hazard function that
generated the data — they are NOT evidence of real-world accuracy.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

import numpy as np
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import brier_score_loss, classification_report, roc_auc_score
from sklearn.model_selection import train_test_split

from ..config import ARTIFACT_DIR
from .synthetic import FEATURE_NAMES, generate_dataset

MODEL_PATH = ARTIFACT_DIR / "risk_model.joblib"
METRICS_PATH = ARTIFACT_DIR / "metrics.json"


def build_model(kind: str = "gradient_boosting"):
    """Return the estimator for `kind`.

    Gradient boosting is the default and is used *uncalibrated*: its logistic
    link already yields smooth probabilities in the open interval (0, 1).
    That matters for this app — isotonic calibration clamps extreme scores to
    exactly 0.0/1.0, which would flatten the risk gauge at the top of the range
    and silently zero out every counterfactual explanation.

    Random forest votes are poorly calibrated, so that path keeps a sigmoid
    (Platt) wrapper, which is monotone and never saturates.
    """
    if kind == "random_forest":
        base = RandomForestClassifier(
            n_estimators=400,
            max_depth=14,
            min_samples_leaf=8,
            n_jobs=-1,
            random_state=42,
        )
        return CalibratedClassifierCV(base, method="sigmoid", cv=4)

    return GradientBoostingClassifier(
        n_estimators=350,
        learning_rate=0.06,
        max_depth=3,
        subsample=0.85,
        random_state=42,
    )


def train(kind: str = "gradient_boosting", n_samples: int = 24_000) -> dict:
    import joblib

    X, y, p_true = generate_dataset(n_samples=n_samples)
    X_train, X_test, y_train, y_test, _, p_test = train_test_split(
        X, y, p_true, test_size=0.2, random_state=42, stratify=y
    )

    model = build_model(kind)
    model.fit(X_train, y_train)

    proba = model.predict_proba(X_test)[:, 1]
    preds = (proba >= 0.5).astype(int)

    metrics = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": kind,
        "calibration": "sigmoid" if kind == "random_forest" else "none (logistic link)",
        "n_samples": int(n_samples),
        "features": FEATURE_NAMES,
        "positive_rate": float(np.mean(y)),
        "roc_auc": float(roc_auc_score(y_test, proba)),
        "brier": float(brier_score_loss(y_test, proba)),
        # How closely the model tracks the *known* latent probability. Only
        # measurable because the data is synthetic.
        "latent_prob_mae": float(np.mean(np.abs(proba - p_test))),
        "report": classification_report(y_test, preds, output_dict=True, zero_division=0),
        "data_source": "SYNTHETIC — generated by app/ml/synthetic.py. Not real mine data.",
        "disclaimer": (
            "Metrics measure recovery of an artificial hazard function on held-out "
            "synthetic data. They are NOT a claim of real-world rockfall prediction accuracy."
        ),
    }

    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump({"model": model, "features": FEATURE_NAMES, "kind": kind}, MODEL_PATH)
    METRICS_PATH.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    return metrics


if __name__ == "__main__":
    m = train()
    print(f"Saved model -> {MODEL_PATH}")
    print(f"ROC-AUC (synthetic hold-out): {m['roc_auc']:.4f}")
    print(f"Brier score:                  {m['brier']:.4f}")
    print(f"MAE vs latent probability:    {m['latent_prob_mae']:.4f}")
    print("\nNOTE: synthetic data only — no real-world validation.")
